default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= Settings.rails_max_threads.to_i %>
  timeout: <%= Settings.database_timout_in_milliseconds.to_i %>

  # instead of the individual values below, you could use `url: Settings.database_url`
  # e.g. heroku would set this in an ENV DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"

  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  host: <%= Settings.database_host %>

  # The TCP port the server listens on. Defaults to 5432.
  # If your server runs on a different port number, change accordingly.
  port: <%= Settings.database_port.to_i %>

  # The name of the database, typically the name_of_app-environment, e.g. minimal-development
  database: <%= Settings.database_name %>

  # The specified database role being used to connect to postgres.
  # To create additional roles in postgres see `$ createuser --help`.
  # When left blank, postgres will use the default role. This is
  # the same name as the operating system user that initialized the database.
  username: <%= Settings.database_username %>

  # The password associated with the postgres role (username).
  password: <%= Settings.database_password %>

  # Schema search path. The server defaults to $user,public
  # schema_search_path: myapp,sharedapp,public

  # Minimum log levels, in increasing order:
  #   debug5, debug4, debug3, debug2, debug1,
  #   log, notice, warning, error, fatal, and panic
  # Defaults to warning.
  # min_messages: notice

development:
  <<: *default

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake" commands.
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: minimal_test

# We treat all databases as 'production' that are neither local nor CI
production: &production
  <<: *default

staging:
  <<: *production
